/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  AgileTaskNotesPluginSettingTab: () => AgileTaskNotesPluginSettingTab,
  default: () => AgileTaskNotesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/Clients/AzureDevopsClient.ts
var import_obsidian2 = require("obsidian");

// src/VaultHelper.ts
var import_obsidian = require("obsidian");
var VaultHelper = class {
  static logError(error) {
    console.log(error);
    new import_obsidian.Notice("Error occured, see console logs for details. (ctrl+shift+i) to open");
  }
  static createFolders(path, app) {
    if (app.vault.getAbstractFileByPath(path) == null) {
      app.vault.createFolder(path).catch((err) => console.log(err));
    }
  }
  static createFoldersFromList(paths, app) {
    paths.forEach((path) => this.createFolders(path, app));
  }
  static getFileByTaskId(path, id, app) {
    const files = app.vault.getMarkdownFiles();
    const projectPath = path.slice(0, path.lastIndexOf("/"));
    for (let i = 0; i < files.length; i++) {
      let filePath = files[i].path;
      if (filePath.startsWith(projectPath) && filePath.contains(id)) {
        return files[i];
      }
    }
    return void 0;
  }
  static createTaskNotes(path, tasks, template, notename, app) {
    let promisesToCreateNotes = [];
    tasks.forEach((task) => {
      if (this.getFileByTaskId(path, task.id, app) == void 0) {
        promisesToCreateNotes.push(this.createTaskNote(path, task, template, notename, app));
      }
    });
    return promisesToCreateNotes;
  }
  static createKanbanBoard(path, tasks, columns, prefix, teamLeaderMode, app) {
    const filename = `${prefix}-Board`;
    const filepath = path + `/${filename}.md`;
    let boardMD = this.BOARD_TEMPLATE_START;
    columns.forEach((column) => {
      boardMD += "## ";
      boardMD += column;
      boardMD += "\n";
      tasks.forEach((task) => {
        if (task.state === column) {
          let file = this.getFileByTaskId(path, task.id, app);
          if (file != void 0) {
            if (teamLeaderMode) {
              boardMD += `- [ ] [[${file.basename}]] 
 ${task.assignedTo} 
 ${task.title}
`;
            } else {
              boardMD += `- [ ] [[${file.basename}]] 
 ${task.title}
`;
            }
          }
        }
      });
      boardMD += "\n";
    });
    boardMD += this.BOARD_TEMPLATE_END;
    return app.vault.adapter.write(filepath, boardMD);
  }
  static createTaskNote(path, task, template, notename, app) {
    return __async(this, null, function* () {
      const safeTitle = task.title.replace(/[\\/:*?"<>|]/g, "-");
      let filename = notename.replace(/{{TASK_NAME}}/g, safeTitle).replace(/{{TASK_ID}}/g, task.id).replace(/{{TASK_STATE}}/g, task.state).replace(/{{TASK_TYPE}}/g, task.type.replace(/ /g, "")).replace(/{{TASK_ASSIGNEDTO}}/g, task.assignedTo);
      const filepath = path + `/${filename}.md`;
      let content = template.replace(/{{TASK_ID}}/g, task.id).replace(/{{TASK_TITLE}}/g, task.title).replace(/{{TASK_STATE}}/g, task.state).replace(/{{TASK_TYPE}}/g, task.type.replace(/ /g, "")).replace(/{{TASK_ASSIGNEDTO}}/g, task.assignedTo).replace(/{{TASK_LINK}}/g, task.link);
      if (task.dueDate != null) {
        content = content.replace(/{{TASK_DUEDATE}}/g, task.dueDate);
      } else {
        content = content.replace(/{{TASK_DUEDATE}}/g, "");
      }
      if (task.tags != null) {
        content = content.replace(/{{TASK_TAGS}}/g, task.tags);
      } else {
        content = content.replace(/{{TASK_TAGS}}/g, "");
      }
      if (task.desc != null) {
        content = content.replace(/{{TASK_DESCRIPTION}}/g, task.desc);
      } else {
        content = content.replace(/{{TASK_DESCRIPTION}}/g, "");
      }
      if (task.criteria != null) {
        content = content.replace(/{{TASK_CRITERIA}}/g, task.criteria);
      } else {
        content = content.replace(/{{TASK_CRITERIA}}/g, "");
      }
      if (task.testScenarios != null) {
        content = content.replace(/{{TASK_TESTS}}/g, task.testScenarios);
      } else {
        content = content.replace(/{{TASK_TESTS}}/g, "");
      }
      return app.vault.create(filepath, content);
    });
  }
};
VaultHelper.BOARD_TEMPLATE_START = "---\n\nkanban-plugin: basic\n\n---\n\n";
VaultHelper.BOARD_TEMPLATE_END = '\n%% kanban:settings\n```\n{"kanban-plugin":"basic"}\n```%%"';

// src/Task.ts
var Task = class {
  constructor(id, state, title, type, assignedTo, link, desc, criteria, testScenarios, dueDate, tags) {
    this.id = id;
    this.state = state;
    this.title = title;
    this.type = type;
    this.assignedTo = assignedTo;
    this.link = link;
    this.desc = desc;
    this.criteria = criteria;
    this.testScenarios = testScenarios;
    this.dueDate = dueDate;
    this.tags = tags;
  }
};

// src/Clients/AzureDevopsClient.ts
var AZURE_DEVOPS_DEFAULT_SETTINGS = {
  instance: "",
  collection: "",
  project: "",
  team: "",
  usernames: "",
  accessToken: "",
  columns: "Pending,In Progress,In Merge,In Verification,Closed"
};
var TASKS_QUERY = '{"query": "Select [System.Id], [System.Title], [System.State] From WorkItems Where [System.IterationPath] UNDER \\"{0}\\"{1}"}';
var USER_OPERAND = '[Assigned to] = \\"{0}\\"';
var AzureDevopsClient = class {
  constructor(app) {
    this.app = app;
    this.clientName = "AzureDevops";
  }
  update(settings) {
    return __async(this, null, function* () {
      const encoded64PAT = Buffer.from(`:${settings.azureDevopsSettings.accessToken}`).toString("base64");
      const headers = {
        Authorization: `Basic ${encoded64PAT}`,
        "Content-Type": "application/json"
      };
      let BaseURL = "";
      if (settings.azureDevopsSettings.collection) {
        BaseURL = `https://${settings.azureDevopsSettings.instance}/${settings.azureDevopsSettings.collection}/${settings.azureDevopsSettings.project}`;
      } else {
        BaseURL = `https://${settings.azureDevopsSettings.instance}/${settings.azureDevopsSettings.project}`;
      }
      try {
        const iterationResponse = yield (0, import_obsidian2.requestUrl)({
          method: "GET",
          headers,
          url: `${BaseURL}/${settings.azureDevopsSettings.team}/_apis/work/teamsettings/iterations?$timeframe=current&api-version=6.0`
        });
        const currentSprint = iterationResponse.json.value[0];
        const normalizeIterationPath = currentSprint.path.normalize().replace(/\\/g, "\\\\");
        let taskIds;
        if (settings.teamLeaderMode) {
          const tasksReponse = yield (0, import_obsidian2.requestUrl)({
            method: "POST",
            body: TASKS_QUERY.format(normalizeIterationPath, ""),
            headers,
            url: `${BaseURL}/${settings.azureDevopsSettings.team}/_apis/wit/wiql?api-version=6.0`
          });
          taskIds = tasksReponse.json.workItems;
        } else {
          const usernames = settings.azureDevopsSettings.usernames.split(",").map((username) => username.trim().replace("'", "\\'"));
          let multiUserOperands = " AND ";
          for (let i = 0; i < usernames.length; i++) {
            multiUserOperands += USER_OPERAND.format(usernames[i]);
            if (i < usernames.length - 1) {
              multiUserOperands += " OR ";
            }
          }
          const tasksReponse = yield (0, import_obsidian2.requestUrl)({
            method: "POST",
            body: TASKS_QUERY.format(normalizeIterationPath, multiUserOperands),
            headers,
            url: `${BaseURL}/${settings.azureDevopsSettings.team}/_apis/wit/wiql?api-version=6.0`
          });
          taskIds = tasksReponse.json.workItems;
        }
        const normalizedFolderPath = (0, import_obsidian2.normalizePath)(settings.targetFolder + "/" + currentSprint.path);
        VaultHelper.createFolders(normalizedFolderPath, this.app);
        const assignedTasks = yield Promise.all(taskIds.map((task) => (0, import_obsidian2.requestUrl)({
          method: "GET",
          headers,
          url: task.url
        }).then((r) => r.json)));
        let tasks = [];
        assignedTasks.forEach((task) => {
          var _a;
          let assigneeName = "Unassigned";
          const assignee = (_a = task.fields["System.AssignedTo"]) != null ? _a : null;
          if (assignee !== null) {
            assigneeName = assignee["displayName"];
          }
          let tags = task.fields["System.Tags"] || "";
          let replacedTags = tags.split(";").map((part) => part.trim().split(" ").map((word) => word.replace(/\s+/g, "-")).join("-")).filter(Boolean).join(" ");
          const tempDate = new Date(task.fields["Microsoft.VSTS.Scheduling.DueDate"]);
          const dueDate = tempDate && !isNaN(tempDate.getTime()) ? tempDate.toLocaleDateString("en-GB") : "";
          const testScenarios = task.fields["Custom.Testscenarios"] ? task.fields["Custom.Testscenarios"] : "No test scenarios provided";
          const acceptanceCriteria = task.fields["Microsoft.VSTS.Common.AcceptanceCriteria"] ? task.fields["Microsoft.VSTS.Common.AcceptanceCriteria"] : "No acceptance criteria provided";
          const description = task.fields["System.Description"] ? task.fields["System.Description"] : "No description provided";
          tasks.push(new Task(task.id, task.fields["System.State"], task.fields["System.Title"], task.fields["System.WorkItemType"], assigneeName, `https://${settings.azureDevopsSettings.instance}/${settings.azureDevopsSettings.collection}/${settings.azureDevopsSettings.project}/_workitems/edit/${task.id}`, description, acceptanceCriteria, testScenarios, dueDate, replacedTags));
        });
        yield Promise.all(VaultHelper.createTaskNotes(normalizedFolderPath, tasks, settings.noteTemplate, settings.noteName, this.app)).catch((e) => VaultHelper.logError(e));
        if (settings.createKanban) {
          const columnIds = settings.azureDevopsSettings.columns.split(",").map((columnName) => columnName.trim());
          yield VaultHelper.createKanbanBoard(normalizedFolderPath, tasks, columnIds, currentSprint.name, settings.teamLeaderMode, this.app).catch((e) => VaultHelper.logError(e));
        }
      } catch (e) {
        VaultHelper.logError(e);
      }
    });
  }
  setupSettings(container, plugin, settingsTab) {
    container.createEl("h2", { text: "AzureDevops Remote Repo Settings" });
    new import_obsidian2.Setting(container).setName("Instance").setDesc("TFS server name (ex: dev.azure.com/OrgName)").addText((text) => text.setPlaceholder("Enter instance base url").setValue(plugin.settings.azureDevopsSettings.instance).onChange((value) => __async(this, null, function* () {
      plugin.settings.azureDevopsSettings.instance = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian2.Setting(container).setName("Collection").setDesc("The name of the Azure DevOps collection (leave empty if it does not apply)").addText((text) => text.setPlaceholder("Enter Collection Name").setValue(plugin.settings.azureDevopsSettings.collection).onChange((value) => __async(this, null, function* () {
      plugin.settings.azureDevopsSettings.collection = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian2.Setting(container).setName("Project").setDesc("AzureDevops Project ID or project name").addText((text) => text.setPlaceholder("Enter project name").setValue(plugin.settings.azureDevopsSettings.project).onChange((value) => __async(this, null, function* () {
      plugin.settings.azureDevopsSettings.project = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian2.Setting(container).setName("Team").setDesc("AzureDevops Team ID or team name").addText((text) => text.setPlaceholder("Enter team name").setValue(plugin.settings.azureDevopsSettings.team).onChange((value) => __async(this, null, function* () {
      plugin.settings.azureDevopsSettings.team = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian2.Setting(container).setName("Usernames").setDesc("A comma-separated list of usernames you want the tasks of. Simply put your username if you only need your own.").addText((text) => text.setPlaceholder("Enter usernames").setValue(plugin.settings.azureDevopsSettings.usernames).onChange((value) => __async(this, null, function* () {
      plugin.settings.azureDevopsSettings.usernames = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian2.Setting(container).setName("Personal Access Token").setDesc("Your AzureDevops PAT with full access").addText((text) => text.setPlaceholder("Enter your PAT").setValue(plugin.settings.azureDevopsSettings.accessToken).onChange((value) => __async(this, null, function* () {
      plugin.settings.azureDevopsSettings.accessToken = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian2.Setting(container).setName("Column Names").setDesc("Line-separated list of column key names from your team sprint board to be used in Kanban board").addText((text) => text.setPlaceholder("Enter comma-separated list").setValue(plugin.settings.azureDevopsSettings.columns).onChange((value) => __async(this, null, function* () {
      plugin.settings.azureDevopsSettings.columns = value;
      yield plugin.saveSettings();
    })));
  }
};

// src/Clients/GitlabClient.ts
var import_obsidian3 = require("obsidian");
var GITLAB_DEFAULT_SETTINGS = {
  baseUrl: "gitlab.com",
  projectId: "",
  accessToken: "",
  usernames: "",
  boardId: "",
  mode: "milestones",
  useMilestoneName: true,
  columns: "Open,Closed",
  excludeClosed: false
};
var _GitlabClient = class {
  constructor(app) {
    this.app = app;
    this.clientName = "Gitlab";
  }
  update(settings) {
    return __async(this, null, function* () {
      const headers = {
        "PRIVATE-TOKEN": settings.gitlabSettings.accessToken,
        "Content-Type": "application/json"
      };
      const projectId = encodeURIComponent(settings.gitlabSettings.projectId);
      const BaseURL = `https://${settings.gitlabSettings.baseUrl}/api/v4`;
      try {
        if (settings.gitlabSettings.mode === "milestones") {
          yield this.updateMilestonesMode(settings, headers, BaseURL, projectId);
        } else if (settings.gitlabSettings.mode === "board") {
          yield this.updateBoardMode(settings, headers, BaseURL, projectId);
        } else if (settings.gitlabSettings.mode === "user") {
          yield this.updateUserMode(settings, headers, BaseURL, projectId);
        }
      } catch (e) {
        VaultHelper.logError(e);
      }
    });
  }
  updateMilestonesMode(settings, headers, BaseURL, projectId) {
    return __async(this, null, function* () {
      const milestonesResponse = yield (0, import_obsidian3.requestUrl)({
        method: "GET",
        headers,
        url: `${BaseURL}/projects/${projectId}/milestones?state=active`
      });
      if (!milestonesResponse.json.length) {
        VaultHelper.logError("No active milestones found in GitLab project");
        return;
      }
      const currentMilestone = milestonesResponse.json[0];
      const milestoneIdentifier = settings.gitlabSettings.useMilestoneName ? currentMilestone.title.replace(/[^a-zA-Z0-9 -]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-") : currentMilestone.id;
      const normalizedFolderPath = (0, import_obsidian3.normalizePath)(settings.targetFolder + "/milestone-" + milestoneIdentifier);
      VaultHelper.createFolders(normalizedFolderPath, this.app);
      let issues = [];
      if (settings.teamLeaderMode) {
        issues = yield this.fetchAllIssues(`${BaseURL}/projects/${projectId}/issues?milestone=${encodeURIComponent(currentMilestone.title)}&per_page=100`, headers);
      } else {
        const usernames = settings.gitlabSettings.usernames.split(",").map((u) => u.trim());
        const issueArrays = yield Promise.all(usernames.map((username) => this.fetchAllIssues(`${BaseURL}/projects/${projectId}/issues?milestone=${encodeURIComponent(currentMilestone.title)}&assignee_username=${encodeURIComponent(username)}&per_page=100`, headers)));
        issues = issueArrays.flat();
      }
      issues = this.deduplicateIssues(issues);
      const { columnNames, listLabels } = yield this.resolveColumns(settings, headers, BaseURL, projectId);
      const tasks = issues.map((issue) => this.issueToTask(issue, settings, listLabels));
      yield Promise.all(VaultHelper.createTaskNotes(normalizedFolderPath, tasks, settings.noteTemplate, settings.noteName, this.app)).catch((e) => VaultHelper.logError(e));
      if (settings.createKanban) {
        yield VaultHelper.createKanbanBoard(normalizedFolderPath, tasks, columnNames, milestoneIdentifier.toString(), settings.teamLeaderMode, this.app).catch((e) => VaultHelper.logError(e));
      }
    });
  }
  updateBoardMode(settings, headers, BaseURL, projectId) {
    return __async(this, null, function* () {
      const normalizedBaseFolderPath = (0, import_obsidian3.normalizePath)(settings.targetFolder);
      const completedFolder = settings.targetFolder + "/Completed/";
      const normalizedCompletedFolderPath = (0, import_obsidian3.normalizePath)(completedFolder);
      VaultHelper.createFoldersFromList([normalizedBaseFolderPath, normalizedCompletedFolderPath], this.app);
      let issues = [];
      if (settings.teamLeaderMode) {
        issues = yield this.fetchAllIssues(`${BaseURL}/projects/${projectId}/issues?state=all&per_page=100`, headers);
      } else {
        const usernames = settings.gitlabSettings.usernames.split(",").map((u) => u.trim());
        const issueArrays = yield Promise.all(usernames.map((username) => this.fetchAllIssues(`${BaseURL}/projects/${projectId}/issues?state=all&assignee_username=${encodeURIComponent(username)}&per_page=100`, headers)));
        issues = issueArrays.flat();
      }
      issues = this.deduplicateIssues(issues);
      const { columnNames, listLabels } = yield this.resolveColumns(settings, headers, BaseURL, projectId);
      const activeTasks = [];
      const completedTasks = [];
      issues.forEach((issue) => {
        const task = this.issueToTask(issue, settings, listLabels);
        if (issue.state === "closed") {
          completedTasks.push(task);
        } else {
          activeTasks.push(task);
        }
      });
      yield Promise.all(VaultHelper.createTaskNotes(normalizedBaseFolderPath, activeTasks, settings.noteTemplate, settings.noteName, this.app));
      yield Promise.all(VaultHelper.createTaskNotes(normalizedCompletedFolderPath, completedTasks, settings.noteTemplate, settings.noteName, this.app));
      const completedTaskNoteFiles = completedTasks.map((task) => VaultHelper.getFileByTaskId(settings.targetFolder, task.id, this.app)).filter((file) => !!file);
      completedTaskNoteFiles.forEach((file) => this.app.vault.rename(file, (0, import_obsidian3.normalizePath)(completedFolder + file.name)));
      const activeTaskNoteFiles = activeTasks.map((task) => VaultHelper.getFileByTaskId(settings.targetFolder, task.id, this.app)).filter((file) => !!file);
      activeTaskNoteFiles.forEach((file) => this.app.vault.rename(file, (0, import_obsidian3.normalizePath)(settings.targetFolder + "/" + file.name)));
      if (settings.createKanban) {
        yield VaultHelper.createKanbanBoard(normalizedBaseFolderPath, activeTasks.concat(completedTasks), columnNames, settings.gitlabSettings.boardId || "board", settings.teamLeaderMode, this.app);
      }
    });
  }
  updateUserMode(settings, headers, BaseURL, _projectId) {
    return __async(this, null, function* () {
      const stateFilter = settings.gitlabSettings.excludeClosed ? "opened" : "all";
      let issues = [];
      if (settings.teamLeaderMode) {
        issues = yield this.fetchAllIssues(`${BaseURL}/issues?scope=all&state=${stateFilter}&per_page=100`, headers);
      } else {
        const usernames = settings.gitlabSettings.usernames.split(",").map((u) => u.trim());
        const issueArrays = yield Promise.all(usernames.map((username) => this.fetchAllIssues(`${BaseURL}/issues?scope=all&assignee_username=${encodeURIComponent(username)}&state=${stateFilter}&per_page=100`, headers)));
        issues = issueArrays.flat();
      }
      issues = this.deduplicateIssues(issues);
      const columnNames = settings.gitlabSettings.columns.split(",").map((c) => c.trim());
      const listLabels = columnNames.filter((c) => c !== "Open" && c !== "Closed");
      const taskEntries = issues.map((issue) => ({
        task: this.issueToTask(issue, settings, listLabels),
        folderPath: this.getDateFolderPath(settings.targetFolder, issue.created_at)
      }));
      const searchPath = (0, import_obsidian3.normalizePath)(settings.targetFolder + "/_search");
      const newTaskEntries = taskEntries.filter(({ task }) => VaultHelper.getFileByTaskId(searchPath, task.id, this.app) === void 0);
      const tasksByFolder = /* @__PURE__ */ new Map();
      newTaskEntries.forEach(({ task, folderPath }) => {
        if (!tasksByFolder.has(folderPath)) {
          tasksByFolder.set(folderPath, []);
        }
        tasksByFolder.get(folderPath).push(task);
      });
      for (const [folderPath, tasks] of tasksByFolder) {
        VaultHelper.createFolders(folderPath, this.app);
        yield Promise.all(VaultHelper.createTaskNotes(folderPath, tasks, settings.noteTemplate, settings.noteName, this.app)).catch((e) => VaultHelper.logError(e));
      }
      if (settings.createKanban) {
        const normalizedBaseFolderPath = (0, import_obsidian3.normalizePath)(settings.targetFolder);
        VaultHelper.createFolders(normalizedBaseFolderPath, this.app);
        const allTasks = taskEntries.map(({ task }) => task);
        yield VaultHelper.createKanbanBoard(normalizedBaseFolderPath, allTasks, columnNames, "all-issues", settings.teamLeaderMode, this.app).catch((e) => VaultHelper.logError(e));
      }
    });
  }
  getDateFolderPath(targetFolder, createdAt) {
    const date = new Date(createdAt);
    const year = date.getFullYear();
    const monthIndex = date.getMonth();
    const quarter = Math.floor(monthIndex / 3) + 1;
    const monthName = _GitlabClient.MONTH_NAMES[monthIndex];
    return (0, import_obsidian3.normalizePath)(`${targetFolder}/${year}/Q${quarter}/${monthName}`);
  }
  fetchAllIssues(baseUrl, headers) {
    return __async(this, null, function* () {
      let allIssues = [];
      let page = 1;
      while (true) {
        const separator = baseUrl.includes("?") ? "&" : "?";
        const response = yield (0, import_obsidian3.requestUrl)({
          method: "GET",
          headers,
          url: `${baseUrl}${separator}page=${page}`
        });
        allIssues = allIssues.concat(response.json);
        if (response.json.length < 100)
          break;
        page++;
      }
      return allIssues;
    });
  }
  deduplicateIssues(issues) {
    const seen = /* @__PURE__ */ new Set();
    return issues.filter((issue) => {
      if (seen.has(issue.iid))
        return false;
      seen.add(issue.iid);
      return true;
    });
  }
  resolveColumns(settings, headers, BaseURL, projectId) {
    return __async(this, null, function* () {
      if (settings.gitlabSettings.boardId) {
        return this.fetchBoardColumns(BaseURL, projectId, settings.gitlabSettings.boardId, headers);
      }
      const columnNames = settings.gitlabSettings.columns.split(",").map((c) => c.trim());
      const listLabels = columnNames.filter((c) => c !== "Open" && c !== "Closed");
      return { columnNames, listLabels };
    });
  }
  fetchBoardColumns(BaseURL, projectId, boardId, headers) {
    return __async(this, null, function* () {
      const listsResponse = yield (0, import_obsidian3.requestUrl)({
        method: "GET",
        headers,
        url: `${BaseURL}/projects/${projectId}/boards/${boardId}/lists`
      });
      const sortedLists = listsResponse.json.sort((a, b) => a.position - b.position);
      const listLabels = sortedLists.map((list) => list.label.name);
      const columnNames = ["Open", ...listLabels, "Closed"];
      return { columnNames, listLabels };
    });
  }
  issueToTask(issue, settings, boardListLabels) {
    let assigneeName = "Unassigned";
    if (issue.assignees && issue.assignees.length > 0) {
      assigneeName = issue.assignees[0].name;
    } else if (issue.assignee) {
      assigneeName = issue.assignee.name;
    }
    let boardState = "Open";
    if (issue.state === "closed") {
      boardState = "Closed";
    } else {
      for (const label of boardListLabels) {
        if (issue.labels && issue.labels.includes(label)) {
          boardState = label;
          break;
        }
      }
    }
    let tags = "";
    if (issue.labels && issue.labels.length > 0) {
      tags = issue.labels.map((label) => label.replace(/\s+/g, "-")).join(" ");
    }
    const issueType = issue.issue_type ? issue.issue_type.charAt(0).toUpperCase() + issue.issue_type.slice(1) : "Issue";
    let dueDate = "";
    if (issue.due_date) {
      const tempDate = new Date(issue.due_date);
      dueDate = !isNaN(tempDate.getTime()) ? tempDate.toLocaleDateString("en-GB") : "";
    }
    const description = issue.description ? issue.description : "No description provided";
    return new Task(issue.iid.toString(), boardState, issue.title, issueType, assigneeName, issue.web_url, description, void 0, void 0, dueDate, tags);
  }
  setupSettings(container, plugin, settingsTab) {
    container.createEl("h2", { text: "GitLab Remote Repo Settings" });
    new import_obsidian3.Setting(container).setName("Instance URL").setDesc("Your GitLab instance hostname (e.g. gitlab.com or gitlab.yourcompany.com)").addText((text) => text.setPlaceholder("gitlab.com").setValue(plugin.settings.gitlabSettings.baseUrl).onChange((value) => __async(this, null, function* () {
      plugin.settings.gitlabSettings.baseUrl = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian3.Setting(container).setName("Personal Access Token").setDesc("A GitLab Personal Access Token with read_api scope").addText((text) => text.setPlaceholder("Enter your PAT").setValue(plugin.settings.gitlabSettings.accessToken).onChange((value) => __async(this, null, function* () {
      plugin.settings.gitlabSettings.accessToken = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian3.Setting(container).setName("Usernames").setDesc("A comma-separated list of GitLab usernames you want tasks for. Put your username if you only need your own.").addText((text) => text.setPlaceholder("Enter usernames").setValue(plugin.settings.gitlabSettings.usernames).onChange((value) => __async(this, null, function* () {
      plugin.settings.gitlabSettings.usernames = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian3.Setting(container).setName("Mode").setDesc("Milestones: groups issues by active milestone (sprints). Board: shows all project issues. User: fetches all assigned issues across all projects into date-based folders (Year/Quarter/Month).").addDropdown((dropdown) => {
      dropdown.addOption("milestones", "Milestones");
      dropdown.addOption("board", "Board");
      dropdown.addOption("user", "User");
      dropdown.setValue(plugin.settings.gitlabSettings.mode).onChange((value) => __async(this, null, function* () {
        plugin.settings.gitlabSettings.mode = value;
        yield plugin.saveSettings();
        settingsTab.display();
      }));
    });
    if (plugin.settings.gitlabSettings.mode !== "user") {
      new import_obsidian3.Setting(container).setName("Project ID").setDesc("The numeric project ID or URL-encoded path (e.g. 12345 or mygroup%2Fmyproject). Found on the project homepage.").addText((text) => text.setPlaceholder("Enter project ID or path").setValue(plugin.settings.gitlabSettings.projectId).onChange((value) => __async(this, null, function* () {
        plugin.settings.gitlabSettings.projectId = value;
        yield plugin.saveSettings();
      })));
      new import_obsidian3.Setting(container).setName("Board ID").setDesc("The ID of your GitLab issue board (optional). If set, column names are fetched automatically from the board. Found in the board URL.").addText((text) => text.setPlaceholder("Enter Board ID").setValue(plugin.settings.gitlabSettings.boardId).onChange((value) => __async(this, null, function* () {
        plugin.settings.gitlabSettings.boardId = value;
        yield plugin.saveSettings();
      })));
    }
    if (plugin.settings.gitlabSettings.mode === "user") {
      new import_obsidian3.Setting(container).setName("Exclude Closed Issues").setDesc("Only pull issues that are not closed").addToggle((toggle) => toggle.setValue(plugin.settings.gitlabSettings.excludeClosed).onChange((value) => __async(this, null, function* () {
        plugin.settings.gitlabSettings.excludeClosed = value;
        yield plugin.saveSettings();
      })));
    }
    if (plugin.settings.gitlabSettings.mode === "milestones") {
      new import_obsidian3.Setting(container).setName("Use Milestone Name (rather than ID)").setDesc("Uses the milestone's title for the folder name instead of its numeric ID").addToggle((toggle) => toggle.setValue(plugin.settings.gitlabSettings.useMilestoneName).onChange((value) => __async(this, null, function* () {
        plugin.settings.gitlabSettings.useMilestoneName = value;
        yield plugin.saveSettings();
      })));
    }
    if (plugin.settings.gitlabSettings.mode !== "user" && !plugin.settings.gitlabSettings.boardId) {
      new import_obsidian3.Setting(container).setName("Column Names").setDesc('Comma-separated list of column names for the Kanban board. Must include "Open" and "Closed". Middle columns should match your GitLab labels. (Only used when Board ID is not set.)').addText((text) => text.setPlaceholder("Open,In Progress,Review,Closed").setValue(plugin.settings.gitlabSettings.columns).onChange((value) => __async(this, null, function* () {
        plugin.settings.gitlabSettings.columns = value;
        yield plugin.saveSettings();
      })));
    }
  }
};
var GitlabClient = _GitlabClient;
GitlabClient.MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];

// src/Clients/JiraClient.ts
var import_obsidian4 = require("obsidian");
var JIRA_DEFAULT_SETTINGS = {
  baseUrl: "{yourserver}.atlassian.net",
  usernames: "",
  email: "",
  authmode: "basic",
  apiToken: "",
  boardId: "",
  useSprintName: true,
  mode: "sprints",
  excludeBacklog: false
};
var JiraClient = class {
  constructor(app) {
    this.app = app;
    this.clientName = "Jira";
  }
  update(settings) {
    return __async(this, null, function* () {
      let headers = {
        Authorization: "",
        "Content-Type": "application/json"
      };
      if (settings.jiraSettings.authmode == "basic") {
        const encoded64Key = Buffer.from(`${settings.jiraSettings.email}:${settings.jiraSettings.apiToken}`).toString("base64");
        headers.Authorization = `Basic ${encoded64Key}`;
      } else if (settings.jiraSettings.authmode = "bearer") {
        headers.Authorization = `Bearer ${settings.jiraSettings.apiToken}`;
      }
      const BaseURL = `https://${settings.jiraSettings.baseUrl}/rest/agile/1.0`;
      try {
        if (settings.jiraSettings.mode == "sprints") {
          const sprintsResponse = yield (0, import_obsidian4.requestUrl)({
            method: "GET",
            headers,
            url: `${BaseURL}/board/${settings.jiraSettings.boardId}/sprint?state=active`
          });
          const currentSprintId = sprintsResponse.json.values[0].id;
          const currentSprintName = sprintsResponse.json.values[0].name.replace(/Sprint/, "").replace(/Board/, "").replace(/^\s+|\s+$/g, "").replace(/[^a-zA-Z0-9 -]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-");
          const sprintIdentifier = settings.jiraSettings.useSprintName ? currentSprintName : currentSprintId;
          const normalizedFolderPath = (0, import_obsidian4.normalizePath)(settings.targetFolder + "/sprint-" + sprintIdentifier);
          VaultHelper.createFolders(normalizedFolderPath, this.app);
          let tasks = [];
          let issueResponseList = [];
          if (settings.teamLeaderMode) {
            issueResponseList[0] = yield (0, import_obsidian4.requestUrl)({
              method: "GET",
              headers,
              url: `${BaseURL}/board/${settings.jiraSettings.boardId}/sprint/${currentSprintId}/issue?maxResults=1000`
            });
          } else {
            let usernames = settings.jiraSettings.usernames.split(",").map((username) => username.trim().replace("'", "\\'"));
            issueResponseList = yield Promise.all(usernames.map((username) => (0, import_obsidian4.requestUrl)({
              method: "GET",
              headers,
              url: `${BaseURL}/board/${settings.jiraSettings.boardId}/sprint/${currentSprintId}/issue?jql=assignee="${username}"&maxResults=1000`
            })));
          }
          issueResponseList.forEach((issueResponse) => {
            issueResponse.json.issues.forEach((issue) => {
              let assigneeName = "Unassigned";
              let assignee = issue.fields["assignee"];
              if (assignee !== null) {
                assigneeName = assignee["displayName"];
              }
              tasks.push(new Task(issue.key, issue.fields["status"]["name"], issue.fields["summary"], issue.fields["issuetype"]["name"], assigneeName, `https://${settings.jiraSettings.baseUrl}/browse/${issue.key}`, issue.fields["description"]));
            });
          });
          yield Promise.all(VaultHelper.createTaskNotes(normalizedFolderPath, tasks, settings.noteTemplate, settings.noteName, this.app));
          if (settings.createKanban) {
            const boardConfigResponse = yield (0, import_obsidian4.requestUrl)({
              method: "GET",
              headers,
              url: `${BaseURL}/board/${settings.jiraSettings.boardId}/configuration`
            });
            const columnIds = boardConfigResponse.json.columnConfig.columns.map((column) => column.name);
            yield VaultHelper.createKanbanBoard(normalizedFolderPath, tasks, columnIds, sprintIdentifier, settings.teamLeaderMode, this.app);
          }
        } else if (settings.jiraSettings.mode == "kanban") {
          const completedFolder = settings.targetFolder + "/Completed/";
          const normalizedBaseFolderPath = (0, import_obsidian4.normalizePath)(settings.targetFolder);
          const normalizedCompletedfolderPath = (0, import_obsidian4.normalizePath)(completedFolder);
          VaultHelper.createFoldersFromList([normalizedBaseFolderPath, normalizedCompletedfolderPath], this.app);
          let activeTasks = [];
          let completedTasks = [];
          let issueResponseList = [];
          if (settings.teamLeaderMode) {
            issueResponseList[0] = yield (0, import_obsidian4.requestUrl)({
              method: "GET",
              headers,
              url: `${BaseURL}/board/${settings.jiraSettings.boardId}/issue?maxResults=1000`
            });
          } else {
            let usernames = settings.jiraSettings.usernames.split(",").map((username) => username.trim().replace("'", "\\'"));
            issueResponseList = yield Promise.all(usernames.map((username) => (0, import_obsidian4.requestUrl)({
              method: "GET",
              headers,
              url: `${BaseURL}/board/${settings.jiraSettings.boardId}/issue?jql=assignee="${username}"&maxResults=1000`
            })));
          }
          issueResponseList.forEach((issueResponse) => {
            issueResponse.json.issues.forEach((issue) => {
              if (!settings.jiraSettings.excludeBacklog || settings.jiraSettings.excludeBacklog && issue.fields["status"]["name"] !== "Backlog") {
                let assigneeName = "Unassigned";
                let assignee = issue.fields["assignee"];
                if (assignee !== null) {
                  assigneeName = assignee["displayName"];
                }
                let taskObj = new Task(issue.key, issue.fields["status"]["name"], issue.fields["summary"], issue.fields["issuetype"]["name"], assigneeName, `https://${settings.jiraSettings.baseUrl}/browse/${issue.key}`, issue.fields["description"]);
                if (issue.fields["resolution"] != null) {
                  completedTasks.push(taskObj);
                } else {
                  activeTasks.push(taskObj);
                }
              }
            });
          });
          yield Promise.all(VaultHelper.createTaskNotes(normalizedBaseFolderPath, activeTasks, settings.noteTemplate, settings.noteName, this.app));
          yield Promise.all(VaultHelper.createTaskNotes(normalizedCompletedfolderPath, completedTasks, settings.noteTemplate, settings.noteName, this.app));
          const completedTaskNoteFiles = completedTasks.map((task) => VaultHelper.getFileByTaskId(settings.targetFolder, task.id, this.app)).filter((file) => !!file);
          completedTaskNoteFiles.forEach((file) => this.app.vault.rename(file, (0, import_obsidian4.normalizePath)(completedFolder + file.name)));
          const activeTaskNoteFiles = activeTasks.map((task) => VaultHelper.getFileByTaskId(settings.targetFolder, task.id, this.app)).filter((file) => !!file);
          activeTaskNoteFiles.forEach((file) => this.app.vault.rename(file, (0, import_obsidian4.normalizePath)(settings.targetFolder + "/" + file.name)));
          if (settings.createKanban) {
            const boardConfigResponse = yield (0, import_obsidian4.requestUrl)({
              method: "GET",
              headers,
              url: `${BaseURL}/board/${settings.jiraSettings.boardId}/configuration`
            });
            let columnIds = boardConfigResponse.json.columnConfig.columns.map((column) => column.name);
            if (settings.jiraSettings.excludeBacklog) {
              columnIds = columnIds.filter((columnName) => columnName !== "Backlog");
            }
            yield VaultHelper.createKanbanBoard(normalizedBaseFolderPath, activeTasks.concat(completedTasks), columnIds, settings.jiraSettings.boardId, settings.teamLeaderMode, this.app);
          }
        }
      } catch (e) {
        VaultHelper.logError(e);
      }
    });
  }
  setupSettings(container, plugin, settingsTab) {
    container.createEl("h2", { text: "Jira Remote Repo Settings" });
    new import_obsidian4.Setting(container).setName("URL").setDesc("The base URL of your Jira server or {ip:port}").addText((text) => text.setPlaceholder("Enter Jira base URL").setValue(plugin.settings.jiraSettings.baseUrl).onChange((value) => __async(this, null, function* () {
      plugin.settings.jiraSettings.baseUrl = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian4.Setting(container).setName("Usernames").setDesc("A comma-separated list of usernames you want the tasks of. Simply put your username if you only need your own.").addText((text) => text.setPlaceholder("Enter usernames").setValue(plugin.settings.jiraSettings.usernames).onChange((value) => __async(this, null, function* () {
      plugin.settings.jiraSettings.usernames = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian4.Setting(container).setName("Email").setDesc("The email of your Atlassian account for Jira").addText((text) => text.setPlaceholder("Enter Atlassian email").setValue(plugin.settings.jiraSettings.email).onChange((value) => __async(this, null, function* () {
      plugin.settings.jiraSettings.email = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian4.Setting(container).setName("Authorization mode").setDesc("Set the mode of authorization to be used").addDropdown((dropdown) => {
      dropdown.addOption("basic", "Basic Auth");
      dropdown.addOption("bearer", "Personal Access Token");
      dropdown.setValue(plugin.settings.jiraSettings.authmode).onChange((value) => __async(this, null, function* () {
        plugin.settings.jiraSettings.authmode = value;
        yield plugin.saveSettings();
      }));
    });
    new import_obsidian4.Setting(container).setName("API Token").setDesc("The API token generated with your account").addText((text) => text.setPlaceholder("Enter API token").setValue(plugin.settings.jiraSettings.apiToken).onChange((value) => __async(this, null, function* () {
      plugin.settings.jiraSettings.apiToken = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian4.Setting(container).setName("Board ID").setDesc("The ID of your Scrum board (the number in the URL when viewing scrum board in browser) ").addText((text) => text.setPlaceholder("Enter Board ID").setValue(plugin.settings.jiraSettings.boardId).onChange((value) => __async(this, null, function* () {
      plugin.settings.jiraSettings.boardId = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian4.Setting(container).setName("Mode").setDesc("Set the mode corresponding to how you use Jira").addDropdown((dropdown) => {
      dropdown.addOption("sprints", "Sprints");
      dropdown.addOption("kanban", "Kanban");
      dropdown.setValue(plugin.settings.jiraSettings.mode).onChange((value) => __async(this, null, function* () {
        plugin.settings.jiraSettings.mode = value;
        yield plugin.saveSettings();
        settingsTab.display();
      }));
    });
    if (plugin.settings.jiraSettings.mode === "sprints") {
      new import_obsidian4.Setting(container).setName("Use Sprint Name (rather than id)").setDesc("Uses the Sprint's human assigned name").addToggle((text) => text.setValue(plugin.settings.jiraSettings.useSprintName).onChange((value) => __async(this, null, function* () {
        plugin.settings.jiraSettings.useSprintName = value;
        yield plugin.saveSettings();
      })));
    } else if (plugin.settings.jiraSettings.mode === "kanban") {
      new import_obsidian4.Setting(container).setName("Exclude Backlog").setDesc("Enable to prevent creation of issues from the backlog").addToggle((toggle) => toggle.setValue(plugin.settings.jiraSettings.excludeBacklog).onChange((value) => __async(this, null, function* () {
        plugin.settings.jiraSettings.excludeBacklog = value;
        yield plugin.saveSettings();
      })));
    }
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  selectedTfsClient: "AzureDevops",
  targetFolder: "",
  noteTemplate: "# {{TASK_TITLE}}\n#{{TASK_TYPE}}\n\nid: {{TASK_ID}}\nstate: {{TASK_STATE}}\nAssignedTo: {{TASK_ASSIGNEDTO}}\n\nLink: {{TASK_LINK}}\n\n{{TASK_DESCRIPTION}}\n\n#todo:\n- [ ] Create todo list\n- [ ] \n\n## Notes:\n",
  noteName: "{{TASK_TYPE}} - {{TASK_ID}}",
  intervalMinutes: 0,
  createKanban: true,
  teamLeaderMode: false,
  azureDevopsSettings: AZURE_DEVOPS_DEFAULT_SETTINGS,
  jiraSettings: JIRA_DEFAULT_SETTINGS,
  gitlabSettings: GITLAB_DEFAULT_SETTINGS
};
var AgileTaskNotesPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.tfsClientImplementations = {};
  }
  onload() {
    return __async(this, null, function* () {
      const azureDevopsClient = new AzureDevopsClient(this.app);
      const jiraClient = new JiraClient(this.app);
      const gitlabClient = new GitlabClient(this.app);
      this.tfsClientImplementations[azureDevopsClient.clientName] = azureDevopsClient;
      this.tfsClientImplementations[jiraClient.clientName] = jiraClient;
      this.tfsClientImplementations[gitlabClient.clientName] = gitlabClient;
      yield this.loadSettings();
      this.addRibbonIcon("dice", "Update TFS Tasks", () => {
        this.tfsClientImplementations[this.settings.selectedTfsClient].update(this.settings);
        new import_obsidian5.Notice("Updated current tasks successfully!");
      });
      this.addCommand({
        id: "update-tfs-tasks",
        name: "Update TFS Tasks",
        callback: () => {
          this.tfsClientImplementations[this.settings.selectedTfsClient].update(this.settings);
          new import_obsidian5.Notice("Updated current tasks successfully!");
        }
      });
      this.addSettingTab(new AgileTaskNotesPluginSettingTab(this.app, this));
      if (this.settings.intervalMinutes > 0) {
        this.registerInterval(window.setInterval(() => this.tfsClientImplementations[this.settings.selectedTfsClient].update(this.settings), this.settings.intervalMinutes * 6e4));
      }
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
var AgileTaskNotesPluginSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl, plugin } = this;
    containerEl.empty();
    new import_obsidian5.Setting(containerEl).setName("Backend TFS").setDesc("The type of TFS you use.").addDropdown((dropdown) => {
      for (const client in plugin.tfsClientImplementations) {
        dropdown.addOption(client, client);
      }
      dropdown.setValue(plugin.settings.selectedTfsClient).onChange((value) => __async(this, null, function* () {
        plugin.settings.selectedTfsClient = value;
        yield plugin.saveSettings();
        this.display();
      }));
    });
    new import_obsidian5.Setting(containerEl).setName("Team Leader Mode").setDesc("Pulls tasks of entire team and shows usernames in generated Kanban board. (ignores username list)").addToggle((toggle) => toggle.setValue(plugin.settings.teamLeaderMode).onChange((value) => __async(this, null, function* () {
      plugin.settings.teamLeaderMode = value;
      yield plugin.saveSettings();
    })));
    plugin.tfsClientImplementations[plugin.settings.selectedTfsClient].setupSettings(containerEl, plugin, this);
    containerEl.createEl("h2", { text: "Vault Settings" });
    new import_obsidian5.Setting(containerEl).setName("Target Folder (Optional)").setDesc("The relative path to the parent folder in which to create/update Kanban boards").addText((text) => text.setPlaceholder("Enter target folder").setValue(plugin.settings.targetFolder).onChange((value) => __async(this, null, function* () {
      plugin.settings.targetFolder = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian5.Setting(containerEl).setName("Inital Task Content").setDesc("Set the inital content for each new task note. Available variables: {{TASK_ID}}, {{TASK_TITLE}}, {{TASK_TYPE}}, {{TASK_STATE}}, {{TASK_ASSIGNEDTO}}, {{TASK_LINK}}, {{TASK_DESCRIPTION}} Azure/GitLab: {{TASK_DUEDATE}} {{TASK_TAGS}} Azure only: {{TASK_CRITERIA}} {{TASK_TESTS}}").addTextArea((text) => {
      text.setPlaceholder("Initial content in raw markdown format").setValue(this.plugin.settings.noteTemplate).onChange((value) => __async(this, null, function* () {
        try {
          this.plugin.settings.noteTemplate = value;
          yield this.plugin.saveSettings();
        } catch (e) {
          return false;
        }
      }));
      text.inputEl.rows = 8;
      text.inputEl.cols = 50;
    });
    new import_obsidian5.Setting(containerEl).setName("Note Name").setDesc("Set the format of the file name for each task note. Available variables: {{TASK_ID}}, {{TASK_NAME}}, {{TASK_TYPE}}, {{TASK_STATE}}, {{TASK_ASSIGNEDTO}}").addText((text) => text.setPlaceholder("{{TASK_TYPE}} - {{TASK_ID}}").setValue(plugin.settings.noteName).onChange((value) => __async(this, null, function* () {
      plugin.settings.noteName = value;
      yield plugin.saveSettings();
    })));
    new import_obsidian5.Setting(containerEl).setName("Update interval").setDesc("Interval (in minutes) to periodically update the kanban board and notes. Set to 0 for only manual updating. You'll need to restart Obsidian for this to take effect. Note: when an update occurs it will close the kanban board if it is open thus a number over 10 mins is recommended.").addText((text) => text.setPlaceholder("Enter number in minutes").setValue(plugin.settings.intervalMinutes.toString()).onChange((value) => __async(this, null, function* () {
      plugin.settings.intervalMinutes = parseInt(value);
      yield plugin.saveSettings();
    })));
    new import_obsidian5.Setting(containerEl).setName("Create Kanban board?").setDesc("Should a Kanban board be generated for the current sprint (requires the Kanban board plugin in addition to this one)").addToggle((toggle) => toggle.setValue(plugin.settings.createKanban).onChange((value) => __async(this, null, function* () {
      plugin.settings.createKanban = value;
      yield plugin.saveSettings();
    })));
  }
};

/* nosourcemap */